### ISSUE TITLE
默认回复采用空字符串

### ISSUE THREAD

**Issue by jasonren0403** [Twx1213/WeChat805#1]
不然容易出现“该公众号提供的服务出现故障，请稍后再试”
source：
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140453
“微信服务器在五秒内收不到响应会断掉连接，并且重新发起请求，总共重试三次。假如服务器无法保证在五秒内处理并回复，

可以直接回复空串，微信服务器不会对此作任何处理，并且不会发起重试。详情请见“发送消息-被动回复消息”。”
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140543
“假如服务器无法保证在五秒内处理并回复，必须做出下述回复，这样微信服务器才不会对此作任何处理，并且不会发起重试（这种情况下，可以使用客服消息接口进行异步回复），否则，将出现严重的错误提示。详见下面说明：

1、直接回复success（推荐方式） 2、直接回复空串（指字节长度为0的空字符串，而不是XML结构体中content字段的内容为空）”

**Comment by Tiko-Lz1e** [comment]
这次是因为选用了存储临时素材imageid的方式来发送图片，结果临时素材到期了，imageid还没改，所以发不出去😂并不是默认回复的问题。
我现在希望用户发送的每条消息都能有响应，尽量保证五秒之内可以完成操作。但实际上由于码力和更新方式的限制，还是会有宕机的时候，以后会尽量避免。
